[profile.default]
  src                = "contracts"
  test               = "test"
  script             = "script"
  out                = "out"
  libs               = ["lib"]
  auto_detect_solc   = true
  optimizer          = true
  optimizer_runs     = 800
  remappings         = [
    "openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
  ]

[fmt]
  line_length     = 100
  tab_width       = 4
  bracket_spacing = true
  multiline_func_header = "params_first"

[rpc_endpoints]
  alfajores = "${ALFAJORES_RPC_URL}"
  celo      = "${CELO_RPC_URL}"

[etherscan]
  alfajores = { key = "${CELOSCAN_API_KEY}", url = "https://api-alfajores.celoscan.io/api" }
  celo      = { key = "${CELOSCAN_API_KEY}", url = "https://api.celoscan.io/api" }
